<?php $url = $this->getUrl('military/index/fileupload'); ?>
<?php $urlEmailCheck = $this->getUrl('military/index/emailchecker'); ?>
<form id="pl_ajax_file_upload" style="display: none"><input type="file" name="pl_ajax_file_upload"></form>
<form class="credit__application" id="military-form" action="<?php echo $block->getFormAction() ?>" data-mage-init='{"validation":{}}' method="post">
        <div class="four__field fieldset">
            <div class="field required">
                <div class="control">
                    <label class="label"><?= $escaper->escapeHtmlAttr(__('First Name')) ?></label>
                    <input type="text" name="name" class="input-text" value="" data-validate='{"required":true}'>
                    <div class="focus-border"></div><!-- focus-border -->
                </div><!-- control -->
            </div><!-- field -->
            <div class="field required">
                <div class="control">
                    <label class="label"><?= $escaper->escapeHtmlAttr(__('Last Name')) ?></label>
                    <input type="text" name="lastname" class="input-text" value="" data-validate='{"required":true}'>
                    <div class="focus-border"></div><!-- focus-border -->
                </div><!-- control -->
            </div><!-- field -->
            <div class="field required">
                <div class="control">
                    <label class="label"><?= $escaper->escapeHtmlAttr(__('Email Address')) ?></label>
                    <input type="text" name="email" id="email_address" class="input-text" value="" data-validate='{"required":true,"validate-emails": true}'>
                    <div style="display:none;color: #e02b27;" id="email-success-msg" class="">This Email is already exist, Please try with another Email.</div>
                    <div class="focus-border"></div><!-- focus-border -->
                </div><!-- control -->
            </div><!-- field -->
            <div class="field required">
                <div class="control">
                    <div class="pluploader upload__file" id="pl-res-cer-upload-btn">
                        <input type="hidden" title="Upload Signature" name="pllegelsignature" id="pldealerupload" data-validate='{"required":true}'>
                        <label class="label file" >
                            <span class="fileupload-btn"><img src="<?= $block->getViewFileUrl('images/fileuploader.png'); ?>" /></span>
                            <span class="upload__signature__title"><?= $escaper->escapeHtml(__('Upload Military Document')) ?></span>
                        </label>
                    </div>
                    <div style="display:none" id="pl-preview-file"><a href='javascript:void(0);' id="pl-remove-file">Remove</a></div>
                    <div style="display:none;color: green;" id="pl-success-msg"></div>
                    <div style="display:none" id="pl-error-msg"></div>
                </div><!-- control -->
            </div><!-- field -->
            <div class="field password required">
                <div class="control">
                    <label for="password" class="label"><span><?= $escaper->escapeHtml(__('Password')) ?></span></label>
                    <input type="password" name="password" id="password"
                                title="<?= $escaper->escapeHtmlAttr(__('Password')) ?>" class="input-text"
                                data-password-min-length="<?= $escaper->escapeHtmlAttr($block->getMinimumPasswordLength()) ?>"
                                data-password-min-character-sets="<?= $escaper->escapeHtmlAttr($block->getRequiredCharacterClassesNumber()) ?>"
                                data-validate="{required:true, 'validate-customer-password':true}" autocomplete="off">
                    <div class="focus-border"></div>
                </div>
                <div id="password-strength-meter-container" data-role="password-strength-meter" aria-live="polite">
                    <div id="password-strength-meter" class="password-strength-meter">
                        Password Strength:
                        <span id="password-strength-meter-label" data-role="password-strength-meter-label">No Password</span>
                    </div>
                </div>
            </div>
            <div class="field confirmation required">
                <div class="control">
                    <label for="password-confirmation" class="label"><span><?= $escaper->escapeHtml(__('Confirm Password')) ?></span></label>
                    <input type="password" name="password_confirmation" title="<?= $escaper->escapeHtmlAttr(__('Confirm Password')) ?>"
                                id="password-confirmation" class="input-text" data-validate="{required:true, equalTo:'#password'}" autocomplete="off">
                    <div class="focus-border"></div>
                </div>
            </div> 
        </div>
        <div class="submit__form">
            <input type="submit" id="submit-form" value="Submit">
        </div><!-- submit__form -->
</form>
<script type="text/javascript">
require(['jquery',"mage/translate",'Magento_Customer/js/zxcvbn' ,'jquery/ui'], function($,$t,zxcvbn){
    $(document).ready(function(){

        $("#military-form #password").change(function(){
            _calculateStrength();
        });
        $("#military-form #password").keyup(function(){
            _calculateStrength();
        });

        $("#military-form #email_address").change(function(){
            _emailChecker();
        });

        //personal Signature Upload functionality
        $(".pluploader").on("click", plfileUpload);
        $("#pl_ajax_file_upload input").on("change", plsubmitUploadFile);
        function plfileUpload(){
            $("#pl_ajax_file_upload input").click();
        }
        function plsubmitUploadFile(){
            var data = $("#pl_ajax_file_upload").get(0);

            $.ajax({
                url: '<?= $url ?>' + "?isAjax=true",
                type: "POST",
                data: new FormData(data),
                processData: false,
                contentType: false,
                showLoader: true,
                success: function (response) {
                    if (response.error) {
                        $("#pldealerupload").val("");
                        $("#pl-res-cer-upload-btn").show();
                        $("#pl-preview-file").hide();
                        $("#pl-success-msg").hide();
                    } else {
                        if (response.data.path) {
                            $("#pl-remove-file").before("<a target='_blank' id='pl-view-image' href='"+response.data.path+"'>View</a>");
                        }
                        if (response.data.filename) {
                            $("#pldealerupload").val(response.data.filename);
                        }
                        $("#pl-res-cer-upload-btn").show();
                        $("#pl-preview-file").show();
                        $("#pl-remove-file").show();
                    }
                    if (response.error == true) {
                        $("#pl-error-msg").html(response.message);
                        $("#pl-error-msg").show();
                        $("#pl-success-msg").hide();
                    }else if(response.message) {
                        $("#pl-success-msg").html(response.message);
                        $("#pl-success-msg").show();
                        $("#pl-error-msg").hide();
                    }
                    $("#pl_ajax_file_upload")[0].reset();
                },
                error: function (response) {
                    $("#pl_ajax_file_upload")[0].reset();
                }
            });
        }
        $("#pl-remove-file").click(function () {
            $("#pldealerupload").val("");
            $("#pl-res-cer-upload-btn").show();
            $("#pl-preview-file").hide();
            $("#pl-view-image").remove();
            $("#pl-remove-file").hide();
            $("#pl-error-msg").hide();
            $("#pl-success-msg").hide();
        });
        $("#submit-form").click(function (){
            if($("#pldealerupload").val() == ''){
                $("#pl-error-msg").html("<span style='color:#e02b27'>This is a required field.</span>");
                $("#pl-error-msg").show();
            }
        });
        $('#military-form').submit(function() {
            if(($("#pldealerupload").val() == ''))
            {
                return false;
            }
            if($("#password-strength-meter-container").hasClass("password-weak") || $("#password-strength-meter-container").hasClass("password-medium"))
            {
                return false;   
            }
            if($("#email-success-msg").hasClass("email-success-msg-class"))
            {
                return false;
            }
        });

        function _emailChecker()
        {
            var emailcheck = $("#military-form #email_address").val();
            var urlaction = '<?= $urlEmailCheck ?>'+ "?isAjax=true";
            $.ajax({
                type: "POST",
                url: urlaction,
                data: {'email': emailcheck},
                showLoader: true,
                success: function(response,e) {
                    if (parseInt(response.data) == 1) {
                        $('#email-success-msg').show();
                        $('#email-success-msg').addClass('email-success-msg-class');
                    } else {
                        $('#email-success-msg').hide();
                        $('#email-success-msg').removeClass('email-success-msg-class');
                    }
                }
            });
        }

        /*Password Functionality*/
        
        function _calculateStrength()
        {
            var password = $("#military-form #password").val(),
            isEmpty = password.length === 0,
            zxcvbnScore,
            displayScore,
            isValid;

            // Display score is based on combination of whether password is empty, valid, and zxcvbn strength
            if (isEmpty) {
                displayScore = 0;
            } else {
                $("#military-form #password").rules('add', {
                    'password-not-equal-to-user-name': $("#military-form #email_address").val()
                });

                // We should only perform this check in case there is an email field on screen
                if ($("#military-form #email_address").length &&
                    password.toLowerCase() === $("#military-form #email_address").val().toLowerCase()
                ) {
                    displayScore = 1;
                } else {
                    isValid = $.validator.validateSingleElement($("#military-form #password"));
                    zxcvbnScore = zxcvbn(password).score;
                    displayScore = isValid && zxcvbnScore > 0 ? zxcvbnScore : 1;
                }
            }
            _displayStrength(displayScore);
        }
        function _displayStrength(displayScore) {
            var strengthLabel = '',
                className,
                color;
            switch (displayScore) {
                case 0:
                    strengthLabel = $t('No Password');
                    className = 'password-none';
                    color = '#f4f4f4';
                    break;

                case 1:
                    strengthLabel = $t('Weak');
                    className = 'password-weak';
                    color = '#ffafae';
                    break;

                case 2:
                    strengthLabel = $t('Medium');
                    className = 'password-medium';
                    color = '#ffd6b3';
                    break;

                case 3:
                    strengthLabel = $t('Strong');
                    className = 'password-strong';
                    color = '#c5eeac';
                    break;

                case 4:
                    strengthLabel = $t('Very Strong');
                    className = 'password-very-strong';
                    color = '#81b562';
                    break;
            }
            $("#password-strength-meter-container")
                .removeClass()
                .addClass(className);
            $("#password-strength-meter-container").css("background-color", color);
            $("#password-strength-meter-label").text(strengthLabel);
        }
    });
});
</script>
