<?php
/**
 * Plumrocket Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End-user License Agreement
 * that is available through the world-wide-web at this URL:
 * http://wiki.plumrocket.net/wiki/EULA
 * If you are unable to obtain it through the world-wide-web, please
 * send an email to support@plumrocket.com so we can send you a copy immediately.
 *
 * @package     Plumrocket_AmpEmail
 * @copyright   Copyright (c) 2019 Plumrocket Inc. (http://www.plumrocket.com)
 * @license     http://wiki.plumrocket.net/wiki/EULA  End-user License Agreement
 */

/** @var \Plumrocket\AmpEmail\Block\Component\State\Wishlist $block */
?>
<amp-state id="<?= $block->escapeHtmlAttr($block->getStateId()) ?>">
    <script type="application/json">
        {
            "status" : <?= $block->escapeJsQuote($block->getProductsWishlistStatus()) ?>,
            "id" : "<?= $block->escapeHtml($block->getIdPrefix()) ?>0"
        }
    </script>
</amp-state>

<form id="atw_form"
      method="POST"
      action-xhr="<?= $block->escapeUrl($block->getAddToWishListUrl()) ?>"
      on="submit-success: AMP.setState({<?= $block->escapeHtml($block->getStateId()) ?>: {status: {[<?= $block->escapeHtml($block->getStateId()) ?>.id]: 1} } });submit-error: AMP.setState({<?= $block->escapeHtml($block->getStateId()) ?>: {status: {[<?= $block->escapeHtml($block->getStateId()) ?>.id]: 0} } })"
>
    <input type="hidden"
           name="product"
           value="<?= $block->escapeHtmlAttr($block->getIdPrefix()) ?>0"
           [value]="<?= $block->escapeHtmlAttr($block->getStateId()) ?>.id"
    />
</form>