<?php
$paymentConfig = $this->getPaymentConfig();
$ccTypes = $paymentConfig->getCcTypes();
$months = $paymentConfig->getMonths();
$years = $paymentConfig->getYears();

?>
<?php if ($block->hasMethods()): ?>

    <?php if ($block->getPayAllInstallments()) { ?>
        <div class="payall-maindiv">
            <p class="payall-p">
                <input type="checkbox" name="payall" class="input checkbox payall" id="payall" value="">
                <label for="payall"><?php echo __('Pay all Installments') ?></label>
            </p>
        </div>
    <?php } ?>

    <div id="order-billing_method">
        <h3><?php echo __('Payment Methods') ?></h3>
        <div id="order-billing_method_form" class="checkout-payment-method">
            <dl class="admin__payment-methods">
                <?php
                $_methods = $block->getMethods();
                $_methodsCount = sizeof($_methods);
                $_counter = 0;
                ?>
                <?php foreach ($_methods as $_method): $_code = $_method->getCode();
                    $_counter++;
                    ?>
                    <dt class="admin__field-option">
                        <?php if ($_methodsCount > 1): ?>
                            <input id="p_method_<?php /* @escapeNotVerified */
                            echo $_code ?>" value="<?php /* @escapeNotVerified */
                            echo $_code ?>" type="radio" name="payment_method"
                                   title="<?php echo $block->escapeHtml($_method->getTitle()) ?>"
                                   class="paymentmethod"<?php if ($block->getSelectedMethodCode() == $_code): ?> checked="checked"<?php endif; ?>
                                   class="admin__control-radio<?php if ($_counter == $_methodsCount) : ?> validate-one-required-by-name<?php endif; ?>"/>
                        <?php else : ?>
                            <span class="no-display">
                            <input id="p_method_<?php /* @escapeNotVerified */
                            echo $_code ?>" value="<?php /* @escapeNotVerified */
                            echo $_code ?>" type="radio"
                                   name="payment_method" class="paymentmethod admin__control-radio"
                                   checked="checked"/>
                        </span>
                        <?php endif; ?>

                        <label class="admin__field-label" for="p_method_<?php /* @escapeNotVerified */
                        echo $_code ?>"><?php echo $block->escapeHtml($_method->getTitle()) ?></label>
                    </dt>
                    <dd class="admin__payment-method-wapper">
                        <?php if ($_code == 'authorizenet_directpost') {
                            $cards = $this->helper('Meetanshi\Partialpro\Helper\Data')->getCardsByMethods($_code);
                            ?>
                            <fieldset class="fieldset payment items ccard authorizenet_directpost"
                                      id="payment_form_authorizenet_directpost"
                                      style="<?php if ($block->getSelectedMethodCode() == $_code) {
                                          echo 'display: block';
                                      } else {
                                          echo 'display: none';
                                      } ?>;margin-top: 20px;margin-bottom: 20px">
                                <legend class="legend">
                                    <span>
                                        <span><?php echo __('Credit Card Information') ?></span>
                                    </span>
                                </legend>
                                <div class="field required">
                                    <label for="<?php echo $_code ?>_cc_type" class="label">
                                        <?php echo __('Credit Card Type') ?>
                                    </label>
                                    <div class="input-box">
                                        <select id="<?php echo $_code ?>_cc_type" name="<?php echo $_code ?>[cc_type]"
                                                class="required-entry validate-cc-type-select"
                                                title="<?php echo __('Credit Card Type') ?>" autocomplete="off">
                                            <option value=""><?php echo __('--Please Select--') ?></option>
                                            <?php
                                            foreach ($ccTypes as $code => $label):
                                                if (in_array($code, $cards)):
                                                    ?>
                                                    <option value="<?php echo $code ?>"><?php echo $label ?></option>
                                                <?php
                                                endif;
                                            endforeach;
                                            ?>
                                        </select>
                                    </div>
                                </div>
                                <div class="field number required">
                                    <label class="label" for="authorizenet_directpost_cc_number">
                                        <span>
                                            <span><?php echo __('Credit Card Number') ?></span>
                                        </span>
                                    </label>
                                    <div class="control">
                                        <input type="number" name="<?php echo $_code ?>[cc_number]"
                                               class="input-text required-entry" value=""
                                               id="authorizenet_directpost_cc_number"
                                               title="<?php echo __('Credit Card Number') ?>">
                                    </div>
                                </div>
                                <div class="field date required" id="authorizenet_directpost_cc_type_exp_div">
                                    <label class="label" for="authorizenet_directpost_expiration">
                                        <span>
                                            <span><?php echo __('Expiration Date') ?></span>
                                        </span>
                                    </label>
                                    <div class="control">
                                        <div class="fields group group-2">
                                            <div class="field no-label month">
                                                <div class="control">
                                                    <select id="<?php echo $_code ?>_expiration"
                                                            name="<?php echo $_code ?>[cc_exp_month]"
                                                            class="select select-month validate-cc-exp required-entry"
                                                            id="authorizenet_directpost_expiration">
                                                        <?php foreach ($months as $k => $v): ?>
                                                            <option value="<?php echo $k ? $k : '' ?>"><?php echo $v ?></option>
                                                        <?php endforeach ?>
                                                    </select>

                                                </div>
                                            </div>
                                            <div class="field no-label year">
                                                <div class="control">
                                                    <select id="<?php echo $_code ?>_expiration_yr"
                                                            name="<?php echo $_code ?>[cc_exp_year]"
                                                            class="select select-year required-entry">
                                                        <?php foreach ($years as $k => $v): ?>
                                                            <option value="<?php echo $k ? $k : '' ?>"><?php echo $v ?></option>
                                                        <?php endforeach ?>
                                                    </select>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <?php if ($_method->hasVerification()):
                                    ?>
                                    <div class="field cvv required" id="authorizenet_directpost_cc_type_cvv_div">
                                        <label class="label" for="authorizenet_directpost_cc_cid">
                                        <span>
                                            <span><?php echo __('Card Verification Number') ?></span>
                                        </span>
                                        </label>
                                        <div class="control _with-tooltip">
                                            <input type="number" autocomplete="off"
                                                   class="input-text cvv required-entry"
                                                   name="<?php echo $_code ?>[cc_cid]" value=""
                                                   id="authorizenet_directpost_cc_cid"
                                                   title="<?php echo __('Card Verification Number') ?>">
                                        </div>
                                    </div>
                                <?php
                                endif; ?>
                            </fieldset>
                            <?php
                        } else if ($_code == 'mtn') { ?>

                            <fieldset class="fieldset payment items ccard mtn"
                                      id="payment_form_mtn"
                                      style="<?php if ($block->getSelectedMethodCode() == $_code) {
                                          echo 'display: block';
                                      } else {
                                          echo 'display: none';
                                      } ?>;margin-top: 20px;margin-bottom: 20px">

                                <div class="field mtn_number required" id="mtn_div_mtn_number">
                                    <label class="label" for="mtn_number">
                                        <span>
                                            <span><?php echo __('MTN Number') ?></span>
                                        </span>
                                    </label>
                                    <div class="control _with-tooltip">
                                        <input type="number" autocomplete="off"
                                               class="input-text mtn_number required-entry"
                                               name="mtn_number" value=""
                                               id="mtn_number"
                                               title="<?php echo __('MTN Number') ?>">
                                    </div>
                                </div>

                            </fieldset>
                            <?php
                        } else {
                            echo $block->getChildHtml('payment.method.' . $_code);
                        }
                        ?>
                    </dd>
                <?php endforeach; ?>
            </dl>
            <dl class="pay-button">
                <dt>
                    <button id="pay-installment" class="action primary" title="Pay Installment" type="submit">
                        <span><?php echo __("Pay"); ?></span>
                    </button>
                </dt>
            </dl>
        </div>
        <script>
            require(["jquery"], function ($) {
                $(document).ready(function () {
                    $('#pay-installment').click(function () {
                        var atLeastOneIsChecked = $('input:checkbox').is(':checked');
                        if (atLeastOneIsChecked) {
                            return true;
                        } else {
                            alert("Please select atleast one installment");
                            return false;
                        }
                    });

                    $('.paymentmethod').change(function () {
                        var value = $('.paymentmethod:checked').val();
                        $("*[id*='payment_form_']").hide();
                        $("*[id*='payment_form_'] input").prop('disabled', true);
                        $("*[id*='payment_form_'] select").prop('disabled', true);

                        $('#payment_form_' + value).show();
                        $('#payment_form_' + value + ' input').prop('disabled', false);
                        $('#payment_form_' + value + ' select').prop('disabled', false);
                        $('#payment_form_' + value).css('padding-left', '30px');
                    });


                    $('#payall').change(function () {
                        if (this.checked) {
                            $('input.input.checkbox').prop('checked', true);
                        } else {
                            $('input.input.checkbox').prop('checked', false);
                        }
                    });

                    var value = $('.paymentmethod:checked').val();

                    $("*[id*='payment_form_']").hide();
                    $("*[id*='payment_form_'] input").prop('disabled', true);
                    $("*[id*='payment_form_'] select").prop('disabled', true);

                    $('#payment_form_' + value).show();
                    $('#payment_form_' + value + ' input').prop('disabled', false);
                    $('#payment_form_' + value + ' select').prop('disabled', false);
                    $('#payment_form_' + value).css('padding-left', '30px');

                });
            });
        </script>
    </div>

<?php else: ?>
    <div class="admin__message-empty"><?php /* @escapeNotVerified */
        echo __('No Payment Methods') ?></div>
<?php endif; ?>
<style>
    .payall-maindiv {
        padding: 11px;
        border: 1px solid;
        font-weight: bold;
        font-size: 15px;
        text-transform: uppercase;
        margin: 30px 0;
    }

    p.payall-p {
        margin: 0;
    }
</style>