<fieldset class="admin__fieldset payment-method" id="payment_form_splitit_payment"
          style="display:none">
    <div class="splitit-default-ui grouped">
        <div class="splitit-cc-group">
        <div id="splitit-card-holder-full-name"></div>
        <div id="splitit-card-number"></div>
        <div id="splitit-expiration-date"></div>
        <div id="splitit-cvv"></div>
        <div class="splitit-cc-group-separator"></div>
        </div>

        <div id="installment-picker"></div>
        <div id="payment-schedule"></div>
        <div id="splitit-error-box"></div>
        <div id="splitit-terms-conditions"></div>
        <button id="splitit-btn-pay" type="button" hidden="true"></button>
    </div>
    <input type="hidden" id="splitit_payment_installment_plan_number"
                name="payment[installmentPlanNum]"/>
    <input type="hidden" id="splitit_payment_succeeded"
        name="payment[succeeded]"/>
</fieldset>

