<?php
/**
 * Plumrocket Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End-user License Agreement
 * that is available through the world-wide-web at this URL:
 * http://wiki.plumrocket.net/wiki/EULA
 * If you are unable to obtain it through the world-wide-web, please
 * send an email to support@plumrocket.com so we can send you a copy immediately.
 *
 * @package     Plumrocket_AmpEmail
 * @copyright   Copyright (c) 2019 Plumrocket Inc. (http://www.plumrocket.com)
 * @license     http://wiki.plumrocket.net/wiki/EULA  End-user License Agreement
 */

declare(strict_types=1);

/** @var $block \Magento\Bundle\Block\Sales\Order\Items\Renderer */
// @codingStandardsIgnoreFile
/** @var $_item \Magento\Sales\Model\Order\Item */
$_item = $block->getItem();
$_order = $_item->getOrder();
/** @var Magento\Sales\Model\Order\Item $parentItem */
$parentItem = $block->getItem();
$items = array_merge([$parentItem], $parentItem->getChildrenItems());
$qtyOrdered = $_item->getQtyOrdered() * 1;


/** @var $prampViewModel \Plumrocket\AmpEmail\ViewModel\Sales\Order\Email\Items\DefaultItems */
$prampViewModel = $block->getData('pramp_view_model');
$imageWidth = $prampViewModel->getImageAttribute('pr_amp_cart_page_product_thumbnail', 'width');
$imageHeight = $prampViewModel->getImageAttribute('pr_amp_cart_page_product_thumbnail', 'height');

if ($block->getItemOptions()
    || $_item->getDescription()
    || $this->helper('Magento\GiftMessage\Helper\Message')->isMessagesAllowed('order_item', $_item) && $_item->getGiftMessageId()) {
    $_showlastRow = true;
} else {
    $_showlastRow = false;
}
$_prevOptionId = '';
?>

<?php foreach ($items as $_item) : ?>

    <?php if ($_item->getParentItem()) : ?>
        <?php $attributes = $block->getSelectionAttributes($_item) ?>
        <?php if ($_prevOptionId != $attributes['option_id']) : ?>
            <tr>
                <td class="ordered-table__td ordered-table__td--bundle" colspan="5">
                    <strong><em><?= /* @escapeNotVerified */  $attributes['option_label'] ?></em></strong>
                </td>
            </tr>
            <?php $_prevOptionId = $attributes['option_id'] ?>
        <?php endif; ?>
    <?php endif; ?>
    <?php if (! $_item->getParentItem()) : ?>
        <tr>
            <td class="ordered-table__td">
                <?php $productImage = $prampViewModel->getProductImage($_item); ?>
                <amp-img
                    width="<?= $block->escapeHtmlAttr($imageWidth) ?>"
                    height="<?= $block->escapeHtmlAttr($imageHeight) ?>"
                    layout="fixed"
                    alt="<?= $block->escapeHtmlAttr($productImage->getLabel()) ?>"
                    src="<?= $block->escapeUrl($productImage->getImageUrl()) ?>" >
                </amp-img>
            </td>
            <td class="ordered-table__td">
                <p class="ordered-table__product-name"><?= $block->escapeHtml($_item->getName()) ?></p>
                <p class="ordered-table__product-sku"><?= $block->escapeHtml(__('SKU')) ?>: <?= $block->escapeHtml($block->getSku($_item)) ?></p>
            </td>
            <td class="ordered-table__td">
                <?php if ($qtyOrdered > 1) : ?>
                    <?php $rowTotal = $_item->getRowTotal() ?>
                    <?php $rowTotalInclTax = $_item->getRowTotalInclTax() ?>
                    <?php $_item->setRowTotal($rowTotal / $qtyOrdered) ?>
                    <?php $_item->setRowTotalInclTax($rowTotalInclTax / $qtyOrdered) ?>
                <?php endif; ?>
                <?= /* @escapeNotVerified */  $block->getItemPrice($_item) ?>
                <?php if ($qtyOrdered > 1) : ?>
                    <?php $_item->setRowTotal($rowTotal) ?>
                    <?php $_item->setRowTotalInclTax($rowTotalInclTax) ?>
                <?php endif; ?>
            </td>
            <td class="ordered-table__td ordered-table__product--center">
                <?= $block->escapeHtml($qtyOrdered) ?>
            </td>
            <td class="ordered-table__td ordered-table__td--price ordered-table__td--right">
                <?= /* @escapeNotVerified */  $block->getItemPrice($_item) ?>
            </td>
        </tr>
    <?php else: ?>
        <tr>
            <td class="ordered-table__td ordered-table__td--bundle" colspan="3">
                <p><?= $block->getValueHtml($_item) ?></p>
            </td>
        </tr>
    <?php endif; ?>

<?php endforeach; ?>

<?php if ($_showlastRow) : ?>
    <tr>
        <td colspan="3" class="item-extra">
            <?php if ($block->getItemOptions()) : ?>
                <dl>
                    <?php foreach ($block->getItemOptions() as $option) : ?>
                        <dt><strong><em><?= /* @escapeNotVerified */  $option['label'] ?></em></strong></dt>
                        <dd><?= /* @escapeNotVerified */  $option['value'] ?></dd>
                    <?php endforeach; ?>
                </dl>
            <?php endif; ?>
            <?php if ($_item->getGiftMessageId() && $_giftMessage = $this->helper('Magento\GiftMessage\Helper\Message')->getGiftMessage($_item->getGiftMessageId())): ?>
                <table class="message-gift">
                    <tr>
                        <td>
                            <h3><?= /* @escapeNotVerified */  __('Gift Message') ?></h3>
                            <strong><?= /* @escapeNotVerified */  __('From:') ?></strong> <?= $block->escapeHtml($_giftMessage->getSender()) ?>
                            <br /><strong><?= /* @escapeNotVerified */  __('To:') ?></strong> <?= $block->escapeHtml($_giftMessage->getRecipient()) ?>
                            <br /><strong><?= /* @escapeNotVerified */  __('Message:') ?></strong>
                            <br /><?= $block->escapeHtml($_giftMessage->getMessage()) ?>
                        </td>
                    </tr>
                </table>
            <?php endif; ?>
        </td>
    </tr>
<?php endif; ?>
