<?php
$additions          = $this->getAdditionalData();
$element     		= $this->getElement();
$breakPage          = $element->getData('break_page');
$enableTitle        = $element->getData('enable_title');
$headTitle       	= $element->getData('head_title');
$titleFontSize      = $element->getData('title_font_size');
$titleColor         = $element->getData('title_color');
$enableBorderBottom = $element->getData('enable_border_bottom');
$borderTitleWidth   = $element->getData('border_title_width');
$borderTitleColor   = $element->getData('border_title_color');
$enableStriped      = $element->getData('enable_striped');
$stripedColorDark   = $element->getData('striped_color_dark');
$stripedColorLight  = $element->getData('striped_color_light');
$textFontSize       = $element->getData('text_font_size');
$textColor      	= $element->getData('text_color');
?>
<?= $breakPage ? "<pagebreak />" : "" ?>
<div class="ppbd-product-additional-information">
    <?php if ($enableTitle) { ?>
		<h2 class="head-title" style="font-size:<?= $titleFontSize ?: "initial" ?>; color: <?= $titleColor ?: "initial" ?>;" ><?= $headTitle ?></h2>
	<?php } ?>
	<table style="min-width: 350px; border: none;" class="table table-style">
        <tbody>
        <?php $stt = 0 ?>
        <?php foreach ($additions as $item) { ?>
			<tr class="<?= $item['code'] ?> <?= $stt % 2 == 0 ? 'light' : 'dark' ?>">
				<th class="col label"><?= $item['label'] ?></th>
				<td class="col data"><?= $item['value'] ?></td>
			</tr>
		<?php $stt++ ?>
        <?php } ?>
        </tbody>
    </table>
    <style>
		.ppbd-product-additional-information {
			display: block;
		}
		.ppbd-product-additional-information .head-title {
			margin-bottom:10px;
			padding-bottom: 5px;
			<?php if ($enableBorderBottom) { ?>
			border-bottom: <?= $borderTitleWidth ?: '0' ?>px solid;	
			border-color: <?= $borderTitleColor ?: '#ffffff' ?>;
			<?php } ?>
		}
		.ppbd-product-additional-information .table-style .col {
			padding: 5px 10px;
			font-size: <?= $textFontSize ?: '14' ?>px;
			color: <?= $textColor ?: '#444444' ?>;
		}
		.ppbd-product-additional-information .table-style .col.label {
			width: 45%;
		}
		<?php if ($enableStriped) { ?>
		.ppbd-product-additional-information .table-style .light {
			background-color: <?= $stripedColorLight ?: '#f2f2f2' ?>;
		}
		.ppbd-product-additional-information .table-style .dark {
			background-color: <?= $stripedColorDark ?: '#d9d9d9' ?>;
		}
		<?php } ?>
	</style>
</div>
