<?php 
	use Magento\Framework\App\Action\Action;
	
	$viewMode = 'grid';
	$image = 'category_page_grid';
	$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
	$_product = $this->getLoadProduct($this->getProductId());
	$_productNameStripped = $block->stripTags($_product->getName(), null, true);
	$productImage = $block->getImage($_product, $image);
	$_helper = $this->helper('Magento\Catalog\Helper\Output');
	$builderHelper = $this->helper('MGS\Fbuilder\Helper\Data');
	$hideName = $this->getBlockData('hide_name');
	$hideReview = $this->getBlockData('hide_review');
	$hidePrice = $this->getBlockData('hide_price');
	$hideAddCart = $this->getBlockData('hide_addcart');
	$hideAddWishlist = $this->getBlockData('hide_addwishlist');
	$hideAddCompare = $this->getBlockData('hide_addcompare');
	
	$htmlStructure = $builderHelper->getStoreConfig('fbuilder/html_structure/product_grid');
?>
<?php $swatches = $this->getSwatches(); ?>
<?php $themeHelper = $this->helper('MGS\Mpanel\Helper\Data'); ?>
<?php $themeSettings = $themeHelper->getThemeSettings(); ?>
<?php $lazyLoad = $themeHelper->getStoreConfig('mgstheme/general/lazy_load'); ?>

<?php $_imagehelper = $this->helper('Magento\Catalog\Helper\Image'); ?>



<?php $_image = 'product_thumbnail_image'; ?>
<?php
	$hover_effect = "";
	if ($themeHelper->getStoreConfig('mpanel/catalog/disable_hover_effect')== 1){
		$hover_effect = "disable_hover_effect";
	}
?>

<div class="product-item-info <?php echo $hover_effect ?>" data-container="product-grid">
	<div class="product-top">
		<?php // Product Image ?>
		<?php $size = $themeHelper->getImageSize($this->getRatio()); ?>
		<?php $padding = $themeHelper->getImagePadding($this->getRatio()); ?>
		
		<?php 
			$productImage = $_imagehelper->init($_product, $image)->resize($size['width'], $size['height'])->getUrl();
			$productImageHover = $_imagehelper->init($_product, $_image)->resize($size['width'], $size['height'])->getUrl();

			$baseImage = $productImage;
			$baseImageHover = $productImageHover;

		?>
		
		<a href="<?php  echo $_product->getProductUrl() ?>" class="product photo product-item-photo" style="padding-bottom: <?php echo $padding ?>;"  tabindex="-1">
			
			<img src="<?php echo $baseImage ?>" alt="<?php echo $_productNameStripped ?>" class="img-responsive product-image-photo img-thumbnail"/>
			
			<?php if(basename($_product->getData('thumbnail')) !=  'no_selection'): ?>
				<?php if(basename($_product->getData('thumbnail')) != basename($_product->getData('small_image'))): ?>
					<img src="<?php echo $baseImageHover ?>" alt="<?php echo $_productNameStripped ?>" class="img-responsive img-hover-show" />
				<?php endif ?>
			<?php endif ?>
			
			<div class="product-image-photo"></div>
		</a>
		
		<?php echo $themeHelper->getProductLabel($_product) ?>
		
		<ul class="actions-link">
			<li class="hidden-sm hidden-xs">
				<?php $quickViewHelper = $this->helper('MGS\QuickView\Helper\Data'); ?>
				<?php echo $quickViewHelper->aroundQuickViewHtml($_product); ?>
			</li>
			
			<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && ($hideAddWishlist!=1)): ?>
				<li>
					<button class="action towishlist"
					   title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
					   data-title="<?php echo __('Add to Wish List') ?>"
					   aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
					   data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>'
					   data-action="add-to-wishlist"
					   role="button">
						<i class="pe-7s-like"></i>
					</button>
				</li>
			<?php endif; ?>
			
			
			<?php if($hideAddCompare!=1): ?>
				<?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare'); ?>
				<li>
					<button class="action tocompare"
					   title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
					   data-title="<?php echo __('Add to Compare') ?>"
					   aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
					   data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_product); ?>'
					   role="button">
						<i class="pe-7s-graph3"></i>
					</button>
				</li>
			<?php endif ?>
		</ul>
		
		<?php if($hideAddCart!=1 && $_product->isSaleable()): ?>
			<div>
				<?php $postParams = $block->getAddToCartPostParams($_product); ?>
				<form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $this->getUrl('checkout/cart/add', ['uenc'=>$postParams['data']['uenc'], 'product'=>$postParams['data']['product']]); ?>" method="post">
					<input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
					<input type="hidden" name="uenc" value="<?php /* @escapeNotVerified */ echo $postParams['data']['uenc']; ?>">
					<input name="form_key" type="hidden" value="<?php echo $this->getFormKey() ?>" />
					<button class="action tocart btn-cart" type="submit" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
						<span class="icon pe-7s-shopbag"></span>
						<span class="text"><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
					</button>
				</form>
			</div>
		<?php endif ?>
	</div>
	
	<div class="product details product-item-details">
		<?php if($hideName!=1): ?>
			<h5 class="product name product-item-name">
				<a class="product-item-link"
				   href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
					<?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
				</a>
			</h5>
		<?php endif ?>
		
		<?php echo $this->getLayout()->createBlock('Magento\Swatches\Block\Product\Renderer\Listing\Configurable')->setProduct($_product)->setTextSwatch($swatches)->setTemplate('Magento_Swatches::product/listing/renderer.phtml')->toHtml() ?>
		
		<?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
	</div>
</div>