<?php if ($block->hasMethods()): ?>
    <div id="order-billing_method" style="padding: 25px;">

        <?php if ($block->getPayAllInstallments()){ ?>
            <div class="payall-maindiv">
                <p class="payall-p">
                    <input type="checkbox" name="payall" class="input checkbox payall" id="payall" value="">
                    <label for="payall"><?php echo __('Pay all Installments')?></label>
                </p>
            </div>
        <?php } ?>

        <h3 style="margin-bottom: 5px"><?php echo __('Payment Methods') ?></h3>
        <div id="order-billing_method_form">
            <dl class="admin__payment-methods">
                <?php
                $_methods = $block->getMethods();
                $_methodsCount = sizeof($_methods);
                $_counter = 0;
                ?>
                <?php foreach ($_methods as $_method): $_code = $_method->getCode();
                    $_counter++;
                    ?>
                    <dt class="admin__field-option">
                        <?php if ($_methodsCount > 1): ?>
                            <input id="p_method_<?php /* @escapeNotVerified */
                            echo $_code ?>" value="<?php /* @escapeNotVerified */
                            echo $_code ?>" type="radio" name="payment_method"
                                   title="<?php echo $block->escapeHtml($_method->getTitle()) ?>"
                                   class="paymentmethod"<?php if ($block->getSelectedMethodCode() == $_code): ?> checked="checked"<?php endif; ?>
                                   class="admin__control-radio<?php if ($_counter == $_methodsCount) : ?> validate-one-required-by-name<?php endif; ?>"/>
                        <?php else : ?>
                            <span class="no-display">
                            <input id="p_method_<?php /* @escapeNotVerified */
                            echo $_code ?>" value="<?php /* @escapeNotVerified */
                            echo $_code ?>" type="radio"
                                   name="payment_method" class="admin__control-radio"
                                   checked="checked"/>
                        </span>
                        <?php endif; ?>

                        <label class="admin__field-label" for="p_method_<?php /* @escapeNotVerified */
                        echo $_code ?>"><?php echo $block->escapeHtml($_method->getTitle()) ?></label>
                    </dt>
                    <dd class="admin__payment-method-wapper">
                        <?php /* @escapeNotVerified */
                        echo $block->getChildHtml('payment.method.' . $_code) ?>
                    </dd>
                <?php endforeach; ?>
            </dl>
            <dl class="pay-button">
                <dt>
                    <button id="pay-installment" class="action tocart primary" title="Pay Installment" type="submit">
                        <span><?php echo __("Pay"); ?></span>
                    </button>
                </dt>
            </dl>
        </div>
        <script>
            require(["jquery"], function ($) {
                $(document).ready(function () {
                    $('#pay-installment').click(function () {
                        var atLeastOneIsChecked = $('input:checkbox').is(':checked');
                        if (atLeastOneIsChecked) {
                            return true;
                        } else {
                            alert("Please select atleast one installment");
                            return false;
                        }
                    });

                    $('.paymentmethod').change(function () {
                        var value = $('.paymentmethod:checked').val();
                        $("*[id*='payment_form_']").hide();
                        $('#payment_form_' + value).show();
                        $('#payment_form_' + value).css('padding-left', '30px');
                    });

                    $('#payall').change(function() {
                        if(this.checked) {
                            $('input.input.checkbox').prop('checked', true);
                        }else{
                            $('input.input.checkbox').prop('checked', false);
                        }
                    });
                });
            });
        </script>
    </div>
<?php else: ?>
    <div class="admin__message-empty"><?php /* @escapeNotVerified */
        echo __('No Payment Methods') ?></div>
<?php endif; ?>

<style>
    .payall-maindiv {
        padding: 11px;
        border: 1px solid;
        font-weight: bold;
        font-size: 15px;
        text-transform: uppercase;
        margin: 30px 0;
    }
    p.payall-p {
        margin: 0;
    }
</style>
