<?php 
/*
* @Author : JiteshBaagul
*/
?>

<div id="loading-fixed">
	<div id="loading-center-fixed">
	</div>
</div>
<script type="text/javascript">
require([
		'jquery'
	], function ($) {
		'use strict';
		$(window).load(function() {
			$('#loading-fixed').delay(500).fadeOut('slow');
		});
		$( document ).ready(function() {
			var myVarloader = setInterval(function(){ setLoaderTime() }, 1000);
			function setLoaderTime() {
				$('#loading-fixed').delay(500).fadeOut('slow');
				clearInterval(myVarloader);
			}
		});
});
</script>