<!-- @JiteshBaaggul loader  -->

<div class="jb_loader"></div>


<!--  loader CSS strat from Here -->

<style type="text/css">
	
body.jb-loaded-off .loader-wrapper{
opacity: 0;
  visibility: hidden;
  -webkit-transition: all .5s linear 0s;
  -moz-transition: all .5s linear 0s;
  -ms-transition: all .5s linear 0s;
  -o-transition: all .5s linear 0s;
  transition: all .5s linear 0s;
}

.loader-wrapper {
  height: 100vh;
  width: 100vw;
  background-color: #fff;
  -webkit-box-align: center;
      -ms-flex-align: center;
          align-items: center;
  -webkit-box-pack: center;
      -ms-flex-pack: center;
          justify-content: center;
  position: fixed;
  z-index: 999999999;
  top: 0;
  opacity: 1;
}
.loader-wrapper .jb_loader {
  position: absolute;
  top: 50%;
  left: 50%;
  -webkit-transform: translate(-50%, -50%);
          transform: translate(-50%, -50%);
  width: 50px;
  height: 50px;
  background-color: #3080fc;
  border-radius: 50%;
}
.loader-wrapper .jb_loader:after{
  content: '';
  position: absolute;
  border-radius: 50%;
  top: 50%;
  left: 50%;
  border: 0 solid white;
  -webkit-transform: translate(-50%, -50%);
          transform: translate(-50%, -50%);
  -webkit-animation: loading 1000ms ease-out forwards infinite;
          animation: loading 1000ms ease-out forwards infinite;
  -webkit-transition: all 0.3s ease;
  transition: all 0.3s ease;
}

@-webkit-keyframes loading {
  0% {
    border: 0 solid white;
    -webkit-transition: all 0.3s ease;
    transition: all 0.3s ease;
  }
  20% {
    border: 8px solid white;
    width: 0;
    height: 0;
    -webkit-transition: all 0.3s ease;
    transition: all 0.3s ease;
  }
  100% {
    border: 8px solid white;
    width: 100%;
    height: 100%;
    -webkit-transition: all 0.3s ease;
    transition: all 0.3s ease;
  }
}

@keyframes loading {
  0% {
    border: 0 solid white;
    -webkit-transition: all 0.3s ease;
    transition: all 0.3s ease;
  }
  20% {
    border: 8px solid white;
    width: 0;
    height: 0;
    -webkit-transition: all 0.3s ease;
    transition: all 0.3s ease;
  }
  100% {
    border: 8px solid white;
    width: 100%;
    height: 100%;
    -webkit-transition: all 0.3s ease;
    transition: all 0.3s ease;
  }
}


</style>

<!-- loader CSS End from Here -->