<?php $collection =  $block->getNewsCollection(); ?>
<div class="brands-slide" style="padding: 30px 0;">
 <div class="container">
    <h2 class="filterproduct-title"><span class="content"><strong><?= __('FEATURED IN') ?></strong></span></h2>
    <div class="owl-side-narrow">
      <div class="brands-slider" id="news-slider-custom">
        <div class="owl-carousel">
          <?php foreach($collection as $key => $value) : ?>
            <div class="item">
              <a target="_blank" href="<?= __($value->getLink()) ?>">
                <img src="<?= __($value->getImageupload()) ?>" />
              </a>
            </div>
          <?php endforeach; ?>
        </div>
      </div>
    </div>
  </div>
</div>  
<div class="viewallbtn" style="display: inline-block; vertical-align: middle; width: 100%; text-align: center; padding-top:15px;">
  <a class="btn btn-default" style="font-weight: 400;font-size: 14px;text-transform: uppercase;color: #fff;line-height: 0.5; letter-spacing: 0.05em; padding: 17px 33px; border-radius: 5px; background-color: #2b2b2d;" href="<?php echo $this->getUrl('aumika-news');?>">View All</a>
</div>
<script type="text/javascript">
  require([
    'jquery',
    'owl.carousel/owl.carousel.min'
  ], function ($) {
    $("#news-slider-custom .owl-carousel").owlCarousel({
      autoplay: true,
      autoplayTimeout: 5000,
      autoplayHoverPause: true,
      margin: 20,
      nav: true,
      navText: ["<em class='porto-icon-left-open-big'></em>","<em class='porto-icon-right-open-big'></em>"],
      dots: false,
      loop: true,
      responsive: {
        0: {
          items:2
        },
        640: {
          items:3
        },
        768: {
          items:4
        },
        992: {
          items:5
        },
        1200: {
          items:5
        }
      }
    });
  });
</script>