<?php
    $contacts_config = $this->helper('Smartwave\Porto\Helper\Data')->getConfig('porto_settings/contacts');
    $_infoblock = $contacts_config['infoblock'];
    $_customblock = $contacts_config['customblock'];
    
    if($_customblock) {
        $block = $this->getLayout()->createBlock('Magento\Cms\Block\Block');
        if($block) {
            $block->setBlockId($_customblock);
        }
        if($block){
            echo '<div class="row"><div class="col-md-12">'.$block->toHtml().'</div></div>';
        }
    }
?>
<div class="row">
    <div class="col-md-8"><?php echo $this->getChildHtml('contactForm')?></div>
    <div class="col-md-4 contact-info">
        <div class="contacts-title"><?php echo __('Contact') ?> <b><?php echo __('Details') ?></b></div>
        <?php //echo $_infoblock; ?>

        <div class="row jbContact">
        <div class="col-md-12">
            <i class="porto-icon-location"></i>
            <p>
                2573 152nd Ave NE, Redmond,<br>WA 98052, United States
                <a href="https://g.page/arungemsinternational?share" style="text-decoration: underline;">Find on map</a>
            </p>
        </div>
        </div>

        <div class="row">
        <div class="col-md-12">
            <i class="porto-icon-phone"></i>
            <p><a href="tel:+18888832786">+ 1 888 883 2786</a></p>
        </div>
        </div>
        <!-- <div class="row">
        <div class="col-md-12">
            <i class="porto-icon-mobile"></i>
            <p>201-123-3922</p>
            <p>302-123-3928</p>
        </div>
        </div> -->
        <div class="row">
        <div class="col-md-12">
            <i class="porto-icon-mail-alt"></i>
            <p><a href="mailto:sales@aumika.com">sales@aumika.com</a></p>
        </div>
        </div>
        <div class="row">
        <div class="col-md-12">
            <i class="porto-icon-skype"></i>
            <p><a href="skype:aumika_skype?add">aumika_skype</a></p>
        </div>
        </div>

        <div class="contacts-title"><?php echo __('Schedule phone') ?> <b><?php echo __('Call') ?></b></div>

        <div class="jb_gemologist" style="margin-bottom: 20px;">
            <a href="https://meetings.hubspot.com/tilak1" class="button action primary btn" role="button">
            <i class="fa fa-phone" aria-hidden="true"></i>    
            Gemologist
            </a>
        </div>
        <div class="jb_designer">
            <a href="https://meetings.hubspot.com/tilak1" class="button action primary btn" role="button">
            <i class="fa fa-phone" aria-hidden="true"></i>     
            Jewelry Designer
            </a>
        </div>


    </div>
</div>