<?php
/**
 * Copyright (c) 2020, Zillion Insurance Services, Inc.
 * All rights reserved.
 * Redistribution and use in source and binary forms, with or without modification,
 * are permitted provided that the following conditions are met:
 *   * Redistributions of source code must retain the above copyright notice,
 *     this list of conditions and the following disclaimer.
 *   * Redistributions in binary form must reproduce the above copyright notice,
 *     this list of conditions and the following disclaimer in the documentation
 *     and/or other materials provided with the distribution.
 *   * Neither the name of Zend Technologies USA, Inc. nor the names of its
 *     contributors may be used to endorse or promote products derived from this
 *     software without specific prior written permission.
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
 * ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * @package myzillion
 * @subpackage module-simplified-insurance
 * @author Serfe <info@serfe.com>
 * @copyright 2020 Zillion Insurance Services, Inc.
 * @since 1.0.0
 */

?>
<?php
/* @var $block \MyZillion\SimplifiedInsurance\Block\Adminhtml\System\Config\TestCredentials */
$storeId = $block->getRequest()->getParam('store');
if (!$storeId) {
    $storeId = 'undefined';
}

$websiteId = $block->getRequest()->getParam('website');
if (!$websiteId) {
    $websiteId = 'undefined';
}
?>

<script>
    require([
        'jquery',
        'prototype'
    ], function($){

        var msgSpan = $('#myzillion_result');

        $('#myzillion_check_credentials').click(function () {
            var params = {
                'api_key': $('#myzillion_api_settings_api_key').val(),
                'mode': $('#myzillion_api_settings_test_mode').val(),
                'store': <?= /* @noEscape */ $storeId ?>,
                'website': <?= /* @noEscape */ $websiteId ?>
            };

            if (!params.api_key ||  params.api_key == '') {
                resultText = 'API Key field is empty';
                msgSpan.find('.error').show();
                $('#message').text(resultText);
            } else {

                new Ajax.Request('<?= /* @noEscape */ $block->getAjaxUrl(); ?>', {
                  parameters:     params,
                  loaderArea:     false,
                  asynchronous:   true,
                  onCreate: function() {
                    msgSpan.find('.success').hide();
                    msgSpan.find('.error').hide();
                    msgSpan.find('.processing').show();
                    $('#message').text('');
                  },
                  onSuccess: function(response) {
                    msgSpan.find('.processing').hide();
                    var resultText = '';
                    if (response.responseJSON.status) {
                      resultText = 'API Key is valid';
                      msgSpan.find('.success').show();
                    } else {
                      resultText = 'API Key is not valid. Verify your api_key or contact the MyZillion team.';
                      msgSpan.find('.error').show();
                    }
                    $('#message').text(resultText);
                  }
                });
            }
        });

    });
</script>

<?= /* @noEscape */ $block->getButtonHtml(); ?>
<span class="collect-indicator" id="myzillion_result">
    <img class="processing"  hidden="hidden" style="margin:0 5px"
        src="<?= /* @noEscape */ $block->getViewFileUrl('images/process_spinner.gif'); ?>"/>
    <img class="success"  hidden="hidden" style="margin:-3px 5px"
        src="<?= /* @noEscape */ $block->getViewFileUrl('images/rule_component_apply.gif'); ?>"/>
    <img class="error"  hidden="hidden" style="margin:-3px 5px"
        src="<?= /* @noEscape */ $block->getViewFileUrl('images/rule_component_remove.gif'); ?>"/>
    <span id="message"></span>
</span>
