<?php
/**
 * Plumrocket Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End-user License Agreement
 * that is available through the world-wide-web at this URL:
 * http://wiki.plumrocket.net/wiki/EULA
 * If you are unable to obtain it through the world-wide-web, please
 * send an email to support@plumrocket.com so we can send you a copy immediately.
 *
 * @package     Plumrocket_Affiliate
 * @copyright   Copyright (c) 2016 Plumrocket Inc. (http://www.plumrocket.com)
 * @license     http://wiki.plumrocket.net/wiki/EULA  End-user License Agreement
 */
?>
<?php
    $info = $this->getInfo();
?>
<div class="entry-edit<?php echo $info->getAffiliateId() ? ' entry-active' : '' ?>" id="affiliate-networks" style="display: none;">
    <div class="entry-edit-head">
        <h4 class="icon-head head-billing-address"><?php echo __('Affiliate') ?></h4>
    </div>
    <form action="<?php echo $this->getUrl('praffiliate/affiliate/orderPost') ?>" method="post">
        <input type="hidden" name="affiliate[order_id]" value="<?php echo $this->getOrder()->getId() ?>" />
        <input type="hidden" name="form_key" value="<?php echo $block->getFormKey(); ?>" />
        <fieldset>
            <div id="affiliate_is_transaction_data">
                <table cellspacing="0" class="form-list">
                    <tr>
                        <td class="label">
                            <label for="status"><?php echo __('Affiliate Transaction') ?></label>
                        </td>
                        <td class="value">
                            <select name="affiliate[affiliate_id]" id="affiliate_affiliate_id" class="select">
                                <?php $affiliates = $this->getAffiliateNetworks() ?>
                                <?php if (count($affiliates)) { ?>
                                    <option value=""><?php echo __('No') ?></option>
                                    <?php foreach($affiliates as $affiliate) { ?>
                                        <option value="<?php echo $affiliate->getId() ?>" <?php if ($affiliate->getId() == $info->getAffiliateId()) echo 'selected="selected"' ?>>
                                            <?php echo $this->escapeHtml($affiliate->getData('name')) ?>
                                        </option>
                                    <?php } ?>
                                <?php } else { ?>
                                    <option  value=""><?php echo __('No affiliate networks available') ?></option>
                                <?php } ?>
                            </select>
                        </td>
                    </tr>
                    <tr id="affiliate_comment_hld" <?php if (!$info->getAffiliateId()) echo 'style="display:none;"' ?>>
                        <td class="label">
                            <label for="status"><?php echo __('Comment') ?></label>
                        </td>
                        <td class="value">
                            <textarea name="affiliate[comment]" id="affiliate_comment" class=" textarea" style="height: 50px;"><?php echo $this->escapeHtml($info->getComment()) ?></textarea>
                        </td>
                    </tr>
                    <tr>
                        <td class="label"></td>
                        <td class="value">
                            <button title="<?php echo __('Save Changes') ?>" type="submit" class="save">
                                <span><span><span><?php echo __('Save Changes') ?></span></span></span>
                            </button>
                        </td>
                    </tr>
                </table>
            </div>
        </fieldset>
    </form>
</div>
<script>
    requirejs(['jquery', 'domReady!'], function($) {
        var afBlock = document.getElementById('affiliate-networks');
        var leftBlocks = document.getElementsByClassName('admin__page-section');
        for(var i=0;i<leftBlocks.length;i++) {
            if (i == 1) {
                leftBlocks[i].appendChild(afBlock);
                $(afBlock).show();
                break;
            }
        }
        $('#affiliate_affiliate_id').on('change', function() {
            var commentHld = $('#affiliate_comment_hld');
            if ($(this).val()) {
                commentHld.show();
            } else {
                commentHld.hide();
            }
        });
    });
</script>