<?php
/**
 * Magedelight
 * Copyright (C) 2019 Magedelight <info@magedelight.com>
 *
 * @category Magedelight
 * @package Magedelight_Facebook
 * @copyright Copyright (c) 2019 Mage Delight (http://www.magedelight.com/)
 * @license http://opensource.org/licenses/gpl-3.0.html GNU General Public License,version 3 (GPL-3.0)
 * @author Magedelight <info@magedelight.com>
 */
?>
<div id="progress-main-container" style="display: none;">
    <div class="progress-area-containse">
        <div id="progress-count">0%</div>  
    </div>
    <div class="meter animate">
        <span id="progress" style="width: 1%"><span></span></span>
        <div id="link" style="margin-top: 20px;text-align:center;"><?php echo __('Wait Feed is generating.'); ?></div>
    </div>
</div>

