<?php
/**
 * Plumrocket Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End-user License Agreement
 * that is available through the world-wide-web at this URL:
 * http://wiki.plumrocket.net/wiki/EULA
 * If you are unable to obtain it through the world-wide-web, please
 * send an email to support@plumrocket.com so we can send you a copy immediately.
 *
 * @package     Plumrocket_Newsletterpopup
 * @copyright   Copyright (c) 2018 Plumrocket Inc. (http://www.plumrocket.com)
 * @license     http://wiki.plumrocket.net/wiki/EULA  End-user License Agreement
 */
 ?>

<?php
$helper = $this->helper('Plumrocket\Newsletterpopup\Helper\Data');
$siteKey = $helper->getReCaptchaSiteKey();
?>

    <?php if ($siteKey == null || $siteKey == '') : ?>
    <div class="g-recaptcha-key">
        <?php echo __('To use reCAPTCHA you must get an API key from:'); ?>
        <a href='https://www.google.com/recaptcha' target='_blank'><?php echo __('Create reCAPTCHA'); ?></a>
    </div>
    <?php else : ?>
        <script src='https://www.google.com/recaptcha/api.js'></script>
        <div class="g-recaptcha" data-sitekey="<?php echo $siteKey; ?>"></div>
    <?php endif; ?>
