<?php /** @var \Splitit\PaymentGateway\Block\UpstreamMessaging\UpstreamMessagingFooter $block */ ?>

<!-- Cards placeholder on Footer -->
<?php if ($block->canDisplay()) : ?>
    <div class="splitit-upstream-content_footer">
        <fieldset data-splitit-placeholder="cards" data-splitit-cards="visa,mastercard"></fieldset>
    </div>

    <!-- Getting upstream content script only if canDisplay() returns true -->
    <?= $this->getLayout()->createBlock("Splitit\PaymentGateway\Block\UpstreamMessaging")->setTemplate("Splitit_PaymentGateway::upstream-messaging.phtml")->toHtml(); ?>
<?php endif; ?>
