<?php
$isFlexyLaywayPlan = $block->getIsFlexyLaywayPlan();
$userChooseInstallment = 'none';
if ($isFlexyLaywayPlan) {
    $userChooseInstallment = 'block';
}
$installmentCount = $block->getInstallmentCount();
$isWhole = $block->getApplyPartialPaymentToWhole();
?>

<?php if ($block->getIsPartialPayment() && $block->getAllowedForCustomerGrp() && ($isWhole) && $block->getIsMinimumOrderAmount()) { ?>

    <div class="cart-summary-whole-cart">
        <form class="form contact"
              action="<?= $block->escapeUrl($block->getFormAction()) ?>"
              id="wholecart-form"
              method="post"
              data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
              data-mage-init='{"validation":{}}'>
            <fieldset class="fieldset">
                <legend class="legend"><span><?= $block->escapeHtml(__($block->getProductpageLabel())) ?></legend>
                <br/>

                <div style="display: <?php echo $userChooseInstallment; ?>">
                    <div class="select-installment">
                        <select class="installment-number" id="installment-number" name="installment_number">
                            <?php
                            for ($i = 2; $i <= $installmentCount; $i++) {
                                if ($i == $installmentCount) {
                                    echo "<option selected value='$i'>$i Installment</option>";
                                } else {
                                    echo "<option value='$i'>$i Installment</option>";
                                }
                            }
                            ?>
                        </select>
                    </div>
                </div>

                <div class="part-desc">
                    <?php echo $block->getInstallmentTable(); ?>
                    <div class="desc-backend">
                        <?php echo $block->getProductpageDescrition() ?>
                    </div>
                </div>

            </fieldset>
            <div class="actions-toolbar">
                <div class="primary">
                    <input type="hidden" name="hideit" id="hideit" value=""/>
                    <button style="" type="submit" title="<?= $block->escapeHtmlAttr(__('Apply')) ?>"
                            class="action submit primary">
                        <span><?= $block->escapeHtml(__('Apply')) ?></span>
                    </button>
                </div>
            </div>
        </form>
    </div>
    <style>
        .desc-backend {
            float: left;
            width: 100%;
            margin-top: 20px;
        }

        .cart-summary-whole-cart {
            width: 480px;
            padding: 20px;
            background: #f5f5f5;
            float: left;
            margin-bottom: 20px;
        }

        .part-desc {
            width: calc(100% - 20px);
            background-color: #ebebeb;
            padding: 10px;
            border-radius: 10px;
            float: left;
            margin-top: 20px;
        }

        .installment-summary {
            width: 100%;
            display: block;
            float: left;
        }

        .installment-first-line {
            width: 100%;
            float: left;
        }

        .installment-totle-item {
            width: 100%;
            float: left;
        }

        .installment-downpayment-item {
            width: 100%;
            float: left;
            background-color: #164163;
            color: #fff;
            border-radius: 10px;
            margin-bottom: 1px;
        }

        .installment-paidlater-item {
            width: 100%;
            float: left;
            background-color: #164163;
            color: #fff;
            border-radius: 10px;
            margin-bottom: 1px;
        }

        .installment-first-line span {
            width: calc(33.33% - 1px);
            display: inline-block;
            float: left;
            text-align: center;
            color: #164163;
            font-weight: bold;
            font-size: 15px;
            line-height: 40px;
            border-bottom: 1px solid #434957;
            border-left: 1px solid #434957;
        }

        .installment-line-item {
            width: 100%;
            float: left;
        }

        .installment-line-item span {
            width: calc(33.33% - 1px);
            float: left;
            text-align: center;
            line-height: 25px;
            border-bottom: 1px solid;
            border-left: 1px solid #434957;
        }

        .installment-downpayment-item span {
            width: calc(33.33% - 1px);
            float: left;
            text-align: center;
            line-height: 30px;
            border-left: 1px solid #fff;
        }

        .installment-downpayment-item span:first-child {
            border-left: none;
            width: calc(66.66% - 26px);
            font-size: 15px;
            text-align: right;
            padding-right: 25px;
        }

        .installment-paidlater-item span {
            width: calc(33.33% - 1px);
            float: left;
            text-align: center;
            line-height: 30px;
            border-left: 1px solid #fff;
        }

        .installment-paidlater-item span:first-child {
            border-left: none;
            width: calc(66.66% - 26px);
            font-size: 15px;
            text-align: right;
            padding-right: 25px;
        }

        .installment-line-item span:first-child {
            border-left: none;
        }

        .installment-first-line span:first-child {
            border-left: none;
        }

        .installment-totle-item span {
            width: calc(33.33% - 1px);
            float: left;
            text-align: center;
            line-height: 30px;
            border-left: 1px solid #434957;
        }

        .installment-totle-item span:first-child {
            border-left: none;
            width: calc(66.66% - 26px);
            font-size: 15px;
            text-align: right;
            padding-right: 25px;
        }

        @media only screen and (max-width: 767px) {
            .cart-summary-whole-cart {
                width: calc(100% - 40px);
            }
        }
    </style>

    <script type="text/javascript">
        require(['jquery', 'jquery/ui'], function ($) {

            $('.installment-number').on('change', function (e) {
                var valueSelected = this.value;
                url = "<?php echo $block->getUrl('partialpayment/cart/gettabledata'); ?>";
                if (valueSelected > 0) {
                    postParams = {
                        "numOfInstallment": valueSelected
                    };

                    jQuery.ajax({
                        url: url,
                        type: 'Post',
                        dataType: 'json',
                        showLoader: true,
                        data: postParams
                    }).done(function (transport) {
                        jQuery('.installment-summary').html(transport.html);
                    });
                }
            });
        });
    </script>
<?php } ?>