<?php

use FME\Events\Model\Event\EventList\EventToolbar;
?>
<p class="toolbar-amount" id="toolbar-amount">
    <?php if ($block->getLastPageNumEvent() > 1): ?>
        <?php  echo __('Items %1-%2 of %3',
            '<span class="toolbar-number">' . $block->getFirstNumEvent() . '</span>',
            '<span class="toolbar-number">' . $block->getLastNumEvent() . '</span>',
            '<span class="toolbar-number">' . $block->getTotalNumEvent() . '</span>') ?>
    <?php elseif ($block->getTotalNumEvent() == 1): ?>
        <?php echo __('%1 Item',
           '<span class="toolbar-number">' . $block->getTotalNumEvent() . '</span>') ?>
    <?php else: ?>
        <?php  echo __('%1 Items',
            '<span class="toolbar-number">' . $block->getTotalNumEvent() . '</span>') ?>
    <?php endif; ?>
</p>
