<?php

use FME\Events\Model\Event\EventList\EventToolbar;
$helper = $this->helper('FME\Events\Helper\Data');

?>
<?php if ($block->isEnabledViewSwitcherEvent()): ?>
<div class="modes" style="float: left !important;">
    <?php $_modes = $block->getModesEvent(); ?>
    <?php if ($_modes && count($_modes) > 1): ?>

    <?php foreach ($block->getModesEvent() as $_code => $_label): ?>

        <?php if ($block->isModeActive($_code)): ?>
            <strong title="<?php echo $_label ?>"
                class="modes-mode active mode-<?php echo strtolower($_code); ?>"
                data-value="<?php echo strtolower($_code); ?>">
                <span><?php echo $_label ?></span>

            </strong>
        <?php else: ?>
            <a class="modes-mode mode-<?php echo strtolower($_code); ?>"
               title="<?php echo $_label ?>"
               href="#"
               data-role="mode-switcher"
               data-value="<?php echo strtolower($_code); ?>"
               id="mode-<?php echo strtolower($_code); ?>"
               aria-labelledby="modes-label mode-<?php echo strtolower($_code); ?>">
                <span><?php echo $_label ?></span>
            </a>
            <?php endif; ?>
        <?php endforeach; ?>
        <a class="mode-jb-calender" title="Calendar" href="<?php  echo $this->getUrl().$helper->getEventFinalDetailIdentifier('calendar'); ?>"><strong><?php  echo __('Calendar') ?></strong></a>
    <?php endif; ?>
</div>
<?php endif; ?>