<?php

use FME\Events\Model\Event\EventList\EventToolbar;
?>
<div class="toolbar-sorter sorter" style="float: right !important;">
    <label class="sorter-label" for="sorter"><?php echo __('Sort By') ?></label>
    <select id="sorter" data-role="sorter" class="sorter-options">
        <?php foreach ($block->getAvailableOrdersEvent() as $_key => $_order): ?>
            <option value="<?php echo $_key; ?>"
                <?php if ($block->isOrderCurrentEvent($_key)): ?>
                    selected="selected"
                <?php endif; ?>
                >
                <?php echo $block->escapeHtml(__($_order)) ?>
            </option>
        <?php endforeach; ?>
    </select>
    
</div>
